In [54]:
import pandas as pd

Cargo los datos

In [55]:
df_clase1 = pd.read_csv(r"C:\Users\Ariela\Desktop\Curso IA\Clases Bootcamp\Proyecto SQL\3-Proyecto\data\clase_1.csv", sep=";")

In [77]:
df_clase1["id_promocion"] = (1)

In [78]:
df_clase1.head(2)

,Nombre,Email,Promoción,Fecha_comienzo,Campus,Proyecto_HLF,Proyecto_EDA,Proyecto_BBDD,Proyecto_ML,Proyecto_Deployment,id_promocion
0,Jafet Casals,Jafet_Casals@gmail.com,Septiembre,18/09/2023,Madrid,Apto,No Apto,Apto,Apto,Apto,1
1,Jorge Manzanares,Jorge_Manzanares@gmail.com,Septiembre,18/09/2023,Madrid,Apto,No Apto,Apto,Apto,Apto,1

In [56]:
df_clase1.head(2)

,Nombre,Email,Promoción,Fecha_comienzo,Campus,Proyecto_HLF,Proyecto_EDA,Proyecto_BBDD,Proyecto_ML,Proyecto_Deployment
0,Jafet Casals,Jafet_Casals@gmail.com,Septiembre,18/09/2023,Madrid,Apto,No Apto,Apto,Apto,Apto
1,Jorge Manzanares,Jorge_Manzanares@gmail.com,Septiembre,18/09/2023,Madrid,Apto,No Apto,Apto,Apto,Apto

In [57]:
df_clase2 = pd.read_csv(r"C:\Users\Ariela\Desktop\Curso IA\Clases Bootcamp\Proyecto SQL\3-Proyecto\data\clase_2.csv", sep=";")

In [79]:
df_clase2["id_promocion"] = (2)

In [80]:
df_clase2.head(2)

,Nombre,Email,Promoción,Fecha_comienzo,Campus,Proyecto_HLF,Proyecto_EDA,Proyecto_BBDD,Proyecto_ML,Proyecto_Deployment,id_promocion
0,Guillermo Borrego,Guillermo_Borrego@gmail.com,Febrero,12/02/2024,Madrid,Apto,No Apto,No Apto,Apto,No Apto,2
1,Sergio Aguirre,Sergio_Aguirre@gmail.com,Febrero,12/02/2024,Madrid,Apto,No Apto,Apto,Apto,No Apto,2

In [59]:
df_clase3 = pd.read_csv(r"C:\Users\Ariela\Desktop\Curso IA\Clases Bootcamp\Proyecto SQL\3-Proyecto\data\clase_3.csv", sep=";")

In [81]:
df_clase3["id_promocion"] = (3)

In [82]:
df_clase3.head(2)

,Nombre,Email,Promoción,Fecha_comienzo,Campus,Proyecto_WebDev,Proyecto_FrontEnd,Proyecto_Backend,Proyecto_React,Proyecto_FullSatck,id_promocion
0,Amor Larrañaga,Amor_Larrañaga@gmail.com,Septiembre,18/09/2023,Madrid,Apto,Apto,Apto,Apto,No Apto,3
1,Teodoro Alberola,Teodoro_Alberola@gmail.com,Septiembre,18/09/2023,Madrid,No Apto,No Apto,Apto,No Apto,Apto,3

In [61]:
df_clase4 = pd.read_csv(r"C:\Users\Ariela\Desktop\Curso IA\Clases Bootcamp\Proyecto SQL\3-Proyecto\data\clase_4.csv", sep=";")

In [83]:
df_clase4["id_promocion"] = (4)

In [84]:
df_clase4.head(2)

,Nombre,Email,Promoción,Fecha_comienzo,Campus,Proyecto_WebDev,Proyecto_FrontEnd,Proyecto_Backend,Proyecto_React,Proyecto_FullSatck,id_promocion
0,Teresa Laguna,Teresa_Laguna@gmail.com,Febrero,12/02/2024,Valencia,Apto,Apto,Apto,Apto,Apto,4
1,Estrella Murillo,Estrella_Murillo@gmail.com,Febrero,12/02/2024,Valencia,Apto,Apto,No Apto,Apto,Apto,4

In [85]:
df_alumnos = pd.concat([df_clase1, df_clase2, df_clase3, df_clase4], axis=0)

In [86]:
df_alumnos.head(5)

,Nombre,Email,Promoción,Fecha_comienzo,Campus,Proyecto_HLF,Proyecto_EDA,Proyecto_BBDD,Proyecto_ML,Proyecto_Deployment,id_promocion,Proyecto_WebDev,Proyecto_FrontEnd,Proyecto_Backend,Proyecto_React,Proyecto_FullSatck
0,Jafet Casals,Jafet_Casals@gmail.com,Septiembre,18/09/2023,Madrid,Apto,No Apto,Apto,Apto,Apto,1,NaN,NaN,NaN,NaN,NaN
1,Jorge Manzanares,Jorge_Manzanares@gmail.com,Septiembre,18/09/2023,Madrid,Apto,No Apto,Apto,Apto,Apto,1,NaN,NaN,NaN,NaN,NaN
2,Onofre Adadia,Onofre_Adadia@gmail.com,Septiembre,18/09/2023,Madrid,Apto,Apto,Apto,No Apto,Apto,1,NaN,NaN,NaN,NaN,NaN
3,Merche Prada,Merche_Prada@gmail.com,Septiembre,18/09/2023,Madrid,Apto,No Apto,No Apto,Apto,No Apto,1,NaN,NaN,NaN,NaN,NaN
4,Pilar Abella,Pilar_Abella@gmail.com,Septiembre,18/09/2023,Madrid,Apto,No Apto,Apto,Apto,Apto,1,NaN,NaN,NaN,NaN,NaN

In [88]:
df_alumnos2 = df_alumnos[["Nombre", "Email", "id_promocion"]]

In [98]:
df_alumnos2 = df_alumnos2.rename(columns={"Email": "email"})
df_alumnos2 = df_alumnos2.rename(columns={"Nombre": "nombre"})
df_alumnos2["id_alumno"] = range(1, len(df_alumnos2) + 1)
df_alumnos2 = df_alumnos2[["nombre", "email", "id_promocion"]]
df_alumnos2.head(50)

                  nombre                           email  id_promocion
0           Jafet Casals          Jafet_Casals@gmail.com             1
1       Jorge Manzanares      Jorge_Manzanares@gmail.com             1
2          Onofre Adadia         Onofre_Adadia@gmail.com             1
3           Merche Prada          Merche_Prada@gmail.com             1
4           Pilar Abella          Pilar_Abella@gmail.com             1
5           Leoncio Tena          Leoncio_Tena@gmail.com             1
6        Odalys Torrijos       Odalys_Torrijos@gmail.com             1
7       Eduardo Caparrós      Eduardo_Caparrós@gmail.com             1
8     Ignacio Goicoechea    Ignacio_Goicoechea@gmail.com             1
9      Clementina Santos     Clementina_Santos@gmail.com             1
10         Daniela Falcó         Daniela_Falcó@gmail.com             1
11         Abraham Vélez         Abraham_Vélez@gmail.com             1
12  Maximiliano Menéndez  Maximiliano_Menéndez@gmail.com             1
13         Anita Heredia         Anita_Heredia@gmail.com             1
14             Eli Casas             Eli_Casas@gmail.com             1
0      Guillermo Borrego     Guillermo_Borrego@gmail.com             2
1         Sergio Aguirre        Sergio_Aguirre@gmail.com             2
2        Carlito Carrión       Carlito_Carrión@gmail.com             2
3        Haydée Figueroa       Haydée_Figueroa@gmail.com             2
4          Chita Mancebo         Chita_Mancebo@gmail.com             2
5       Joaquina Asensio      Joaquina_Asensio@gmail.com             2
6       Cristian Sarabia      Cristian_Sarabia@gmail.com             2
7          Isabel Ibáñez         Isabel_Ibáñez@gmail.com             2
8        Desiderio Jordá       Desiderio_Jordá@gmail.com             2
9        Rosalina Llanos       Rosalina_Llanos@gmail.com             2
0         Amor Larrañaga        Amor_Larrañaga@gmail.com             3
1       Teodoro Alberola      Teodoro_Alberola@gmail.com             3
2            Cleto Plana           Cleto_Plana@gmail.com             3
3       Aitana Sebastián      Aitana_Sebastián@gmail.com             3
4       Dolores Valbuena      Dolores_Valbuena@gmail.com             3
5           Julie Ferrer          Julie_Ferrer@gmail.com             3
6         Mireia Cabañas        Mireia_Cabañas@gmail.com             3
7          Flavia Amador         Flavia_Amador@gmail.com             3
8          Albino Macias         Albino_Macias@gmail.com             3
9          Ester Sánchez         Ester_Sánchez@gmail.com             3
10    Luis Miguel Galvez    Luis_Miguel_Galvez@gmail.com             3
11        Loida Arellano        Loida_Arellano@gmail.com             3
12        Heraclio Duque        Heraclio_Duque@gmail.com             3
13     Herberto Figueras     Herberto_Figueras@gmail.com             3
0          Teresa Laguna         Teresa_Laguna@gmail.com             4
1       Estrella Murillo      Estrella_Murillo@gmail.com             4
2        Ernesto Uriarte       Ernesto_Uriarte@gmail.com             4
3        Daniela Guitart       Daniela_Guitart@gmail.com             4
4         Timoteo Trillo        Timoteo_Trillo@gmail.com             4
5          Ricarda Tovar         Ricarda_Tovar@gmail.com             4
6    Alejandra Vilaplana   Alejandra_Vilaplana@gmail.com             4
7        Daniel Rosselló       Daniel_Rosselló@gmail.com             4
8          Rita Olivares         Rita_Olivares@gmail.com             4
9           Cleto Montes          Cleto_Montes@gmail.com             4
10       Marino Castilla       Marino_Castilla@gmail.com             4

In [100]:
def generar_insert(df, tabla):
    valores = []
    for _, row in df.iterrows():
        valor = f"('{row['nombre']}', '{row['email']}', {row['id_promocion']})"
        valores.append(valor)
    
    query = f"INSERT INTO {tabla} (nombre, email, id_promocion) VALUES\n"
    query += ",\n".join(valores) + ";"
    
    return query

print(generar_insert(df_alumnos2, "Alumnos"))

INSERT INTO Alumnos (nombre, email, id_promocion) VALUES
('Jafet Casals', 'Jafet_Casals@gmail.com', 1),
('Jorge Manzanares', 'Jorge_Manzanares@gmail.com', 1),
('Onofre Adadia', 'Onofre_Adadia@gmail.com', 1),
('Merche Prada', 'Merche_Prada@gmail.com', 1),
('Pilar Abella', 'Pilar_Abella@gmail.com', 1),
('Leoncio Tena', 'Leoncio_Tena@gmail.com', 1),
('Odalys Torrijos', 'Odalys_Torrijos@gmail.com', 1),
('Eduardo Caparrós', 'Eduardo_Caparrós@gmail.com', 1),
('Ignacio Goicoechea', 'Ignacio_Goicoechea@gmail.com', 1),
('Clementina Santos', 'Clementina_Santos@gmail.com', 1),
('Daniela Falcó', 'Daniela_Falcó@gmail.com', 1),
('Abraham Vélez', 'Abraham_Vélez@gmail.com', 1),
('Maximiliano Menéndez', 'Maximiliano_Menéndez@gmail.com', 1),
('Anita Heredia', 'Anita_Heredia@gmail.com', 1),
('Eli Casas', 'Eli_Casas@gmail.com', 1),
('Guillermo Borrego', 'Guillermo_Borrego@gmail.com', 2),
('Sergio Aguirre', 'Sergio_Aguirre@gmail.com', 2),
('Carlito Carrión', 'Carlito_Carrión@gmail.com', 2),
('Haydée Figueroa', 'Haydée_Figueroa@gmail.com', 2),
('Chita Mancebo', 'Chita_Mancebo@gmail.com', 2),
('Joaquina Asensio', 'Joaquina_Asensio@gmail.com', 2),
('Cristian Sarabia', 'Cristian_Sarabia@gmail.com', 2),
('Isabel Ibáñez', 'Isabel_Ibáñez@gmail.com', 2),
('Desiderio Jordá', 'Desiderio_Jordá@gmail.com', 2),
('Rosalina Llanos', 'Rosalina_Llanos@gmail.com', 2),
('Amor Larrañaga', 'Amor_Larrañaga@gmail.com', 3),
('Teodoro Alberola', 'Teodoro_Alberola@gmail.com', 3),
('Cleto Plana', 'Cleto_Plana@gmail.com', 3),
('Aitana Sebastián', 'Aitana_Sebastián@gmail.com', 3),
('Dolores Valbuena', 'Dolores_Valbuena@gmail.com', 3),
('Julie Ferrer', 'Julie_Ferrer@gmail.com', 3),
('Mireia Cabañas', 'Mireia_Cabañas@gmail.com', 3),
('Flavia Amador', 'Flavia_Amador@gmail.com', 3),
('Albino Macias', 'Albino_Macias@gmail.com', 3),
('Ester Sánchez', 'Ester_Sánchez@gmail.com', 3),
('Luis Miguel Galvez', 'Luis_Miguel_Galvez@gmail.com', 3),
('Loida Arellano', 'Loida_Arellano@gmail.com', 3),
('Heraclio Duque', 'Heraclio_Duque@gmail.com', 3),
('Herberto Figueras', 'Herberto_Figueras@gmail.com', 3),
('Teresa Laguna', 'Teresa_Laguna@gmail.com', 4),
('Estrella Murillo', 'Estrella_Murillo@gmail.com', 4),
('Ernesto Uriarte', 'Ernesto_Uriarte@gmail.com', 4),
('Daniela Guitart', 'Daniela_Guitart@gmail.com', 4),
('Timoteo Trillo', 'Timoteo_Trillo@gmail.com', 4),
('Ricarda Tovar', 'Ricarda_Tovar@gmail.com', 4),
('Alejandra Vilaplana', 'Alejandra_Vilaplana@gmail.com', 4),
('Daniel Rosselló', 'Daniel_Rosselló@gmail.com', 4),
('Rita Olivares', 'Rita_Olivares@gmail.com', 4),
('Cleto Montes', 'Cleto_Montes@gmail.com', 4),
('Marino Castilla', 'Marino_Castilla@gmail.com', 4),
('Estefanía Valcárcel', 'Estefanía_Valcárcel@gmail.com', 4),
('Noemí Vilanova', 'Noemí_Vilanova@gmail.com', 4);